create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  name varchar(50) not null,
  message varchar(300) not null,
  created_at timestamptz not null default now(),
  approved boolean not null default true,
  constraint wishes_name_not_blank check (char_length(btrim(name)) between 1 and 50),
  constraint wishes_message_not_blank check (char_length(btrim(message)) between 1 and 300)
);

create index if not exists wishes_created_at_desc_idx
  on public.wishes (created_at desc);

alter table public.wishes enable row level security;

revoke all on table public.wishes from anon, authenticated;
grant select on table public.wishes to anon, authenticated;
grant insert (name, message) on table public.wishes to anon, authenticated;
grant usage, select on sequence public.wishes_id_seq to anon, authenticated;

drop policy if exists "Public can read approved wishes" on public.wishes;
create policy "Public can read approved wishes"
  on public.wishes
  for select
  to anon, authenticated
  using (approved = true);

drop policy if exists "Public can submit valid wishes" on public.wishes;
create policy "Public can submit valid wishes"
  on public.wishes
  for insert
  to anon, authenticated
  with check (
    approved = true
    and char_length(btrim(name)) between 1 and 50
    and char_length(btrim(message)) between 1 and 300
  );

-- No public UPDATE or DELETE policy is created intentionally.

do $$
begin
  alter publication supabase_realtime add table public.wishes;
exception
  when duplicate_object then null;
end $$;
